---

name: Convert markdown files
description: Convert certain elements of the provided file to fit the requirements for certain blog page providers

branding:
  icon: arrow-left-circle
  color: green

inputs:
  markdown_file_urls:
    description: 'The urls to the markdown file to convert - expects a comma separated string'
    required: true
  output_dir_code:
    description: 'The inserted code files output directory'
    required: false
    default: ""
  output_dir_admonitions:
    description: 'The replaced admonitions files output directory'
    required: false
    default: ""

runs:
  using: composite
  # TODO figure out how to set up environment variables

  steps:
    - name: Setup Python3.12
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get code files
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python markdown_conversion.py download "${{ inputs.markdown_file_urls }}"

    - name: Show current files
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        echo "Current working directory: $(pwd)"
        echo "Files:"
        ls -R

    - name: Replace code references
      if: inputs.output_dir_code
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python markdown_conversion.py insert-code-references "${{ inputs.output_dir_code }}"

    # TODO Ensure logic can run independent from each other
    # currently update admonitions is dependent on code-replacement
    - name: Update admonitions
      if: inputs.output_dir_admonitions
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python markdown_conversion.py replace-admonitions ${{ inputs.output_dir_code }} ${{ inputs.output_dir_admonitions }}

...
