---

name: Convert markdown files
description: Convert certain elements of the provided file to fit the requirements for certain blog page providers

branding:
  icon: arrow-left-circle
  color: green

inputs:
  domain_url:
    description: 'Url of the code source domain'
    required: false
  markdown_file_path:
    description: 'The path to the markdown file to convert'
    required: true
  code:
    description: 'Convert code blocks to fit the requirements of the blog provider'
    required: false
    default: "false"
  output_file_code:
    description: 'The inserted code files output file path'
    required: true
  admonitions:
    description: 'Convert admonitions to fit the requirements of the blog provider'
    required: false
    default: "false"
  output_file_admonitions:
    description: 'The replaced admonitions files output file path'
    required: true

runs:
  using: composite
  # TODO figure out how to set up environment variables

  steps:
    - name: Setup Python3.12
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Get code files
      if: inputs.code
      shell: bash
      run: |
        python3.12 markdown_conversion.py download-files ${{ inputs.domain_url }} ${{ inputs.markdown_file_path }} 

    - name: Replace code references
      if: inputs.code
      shell: bash
      run: |
        python3.12 markdown_conversion.py insert-code-references ${{ inputs.markdown_file_path }} ${{ inputs.output_file_code }}

    # TODO Ensure logic can run independent from each other
    # currently update admonitions is dependent on code-replacement
    - name: Update admonitions
      shell: bash
      run: |
        python3.12 markdown-conversion.py replace_admonitions ${{ inputs.output_file_code }} ${{ inputs.output_file_admonitions }}

...
