---

name: Unit Testing

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'TODO.md'
      - '**/*.md'
      - .gitignore

env:
  PYTHON_VERSION: "3.12"

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run unit tests
        run: |
          pytest
        working-directory: ${{ github.workspace }}

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest

    env:
      FILE_PATH: "path/to/file.md"

    steps:
      - name: Create test file
        run: |
          curl markdown file to ${{ env.FILE_PATH }}

      - name: Run action
        uses: philnewm/markdown-conversion@main
        with:
          markdown_file_path: ${{ env.FILE_PATH }}
          code: true
          admonitions: true
          target_path: "path/to/output.md"

      - name: Test output
        run:
          if diff -q "path/to/output.md" "path/to/reference.md"; then
            echo "Files are the same"
          else
            echo "Files are different"
            exit 1
          fi

...
