---

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'TODO.md'
      - '**/*.md'
      - .gitignore

env:
  PYTHON_VERSION: "3.12"

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run unit tests
        run: |
          pytest
        working-directory: ${{ github.workspace }}

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest

    env:
      FILE_PATH: "text.md"
      URL: "raw.githubusercontent.com/philnewm/markdown-conversion/refs/heads/main/tests/integrationtests"
      OUTPUT_CODE: "output_code"
      OUTPUT_ADMONITIONS: "output_admonitions"
      REFERENCE_FILE: "reference.md"

    steps:
      # TODO create test files from code
      - name: Get reference file
        run: |
          curl -o ${{ env.REFERENCE_FILE }} https://${{ env.URL }}/${{ env.REFERENCE_FILE }}

      - name: Run action
        uses: philnewm/markdown-conversion@main
        with:
          markdown_file_urls: "https://${{ env.URL }}/${{ env.FILE_PATH }}"
          output_dir_code: ${{ github.workspace }}/${{ env.OUTPUT_CODE }}
          # output_dir_admonitions: ${{ github.workspace }}/${{ env.OUTPUT_ADMONITIONS }}

      - name: Show files
        run: |
          tree -h

      - name: Upload gh_output
        uses: actions/upload-artifact@v4
        with:
          name: gh_output
          path: ${{ github.workspace }}/${{ env.OUTPUT_CODE }}

      - name: Upload devto_output
        uses: actions/upload-artifact@v4
        with:
          name: devto_output
          path: ${{ github.workspace }}/${{ env.OUTPUT_ADMONITIONS }}

      - name: Test output
        run: |
          if diff -q ${{ github.workspace }}/${{ env.OUTPUT_ADMONITIONS }}/${{ env.FILE_PATH }} ${{ github.workspace }}/${{ env.REFERENCE_FILE }}; then
            echo "Files are the same"
          else
            echo "Files are different"
            exit 1
          fi

...
